error_page 413 /errors/413.html;
error_page 500 502 503 504 /errors/500.html;

location = /errors/413.html {
    internal;
    root /var/app/current/public;
}
location = /errors/500.html {
    internal;
    root /var/app/current/public;
}
